{% set version = "2025.07.22" %}

package:
  name: opencl-headers
  version: {{ version }}

source:
  url: https://github.com/KhronosGroup/OpenCL-Headers/archive/v{{ version }}.zip
  sha256: ef9ba8d4231110bb369becb20cb98259d94a448fc8232ede96551c26d110840f

build:
  number: 0
  ignore_run_exports_from:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cmake
    - ninja
    - python
  host:
  run:

test:
  commands:
    - if not exist %LIBRARY_INC%\\CL\\cl.h exit 1                       # [win]
    - if not exist %LIBRARY_LIB%\\pkgconfig\\OpenCL-Headers.pc exit 1   # [win]
    - test -f $PREFIX/include/OpenCL/cl.h                               # [osx]
    - test -f $PREFIX/include/CL/cl.h                                   # [unix]
    - test -f $PREFIX/lib/pkgconfig/OpenCL-Headers.pc                   # [unix]

about:
  home: https://registry.khronos.org/OpenCL/
  license: Apache-2.0
  license_file: LICENSE
  summary: OpenCL headers
  description: C language headers for the OpenCL API.
  dev_url: https://github.com/KhronosGroup/OpenCL-Headers
  doc_url: https://registry.khronos.org/OpenCL/
extra:
  recipe-maintainers:
    - isuruf
